# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QPN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QPN

pod 'SDWebImage', '~>3.7'
pod 'MBProgressHUD', '~> 0.9.2'
pod "MWPhotoBrowser"
pod "VKVideoPlayer", "~> 0.1.1"
pod 'MFSideMenu'
pod 'MaterialControls'
pod 'IQKeyboardManager'
pod 'EMCCountryPickerController'
pod 'SCLAlertView-Objective-C'
pod 'Toast', '~> 3.0'
pod 'WYPopoverController', '~> 0.2.2'
pod 'AFNetworking', '~> 3.0'
pod 'AWSS3'


end
